version: "3"

services:
  home:
    image: door-app.net/home:1.0.0
    build: .
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    stdin_open: true