# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:206.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: インストール docker クライアント
          command: |
            set -x
            VER="18.06.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Authenticate Google Cloud
          command: |
            GOOGLE_PROJECT_ID=door-app-prod
            GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}
            echo ${GCLOUD_SERVICE_KEY} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project door-app-prod
            gcloud --quiet config set compute/zone asia-northeast1-a